# Generated by Django 3.2.7 on 2021-09-25 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notes',
            options={'verbose_name': 'notes', 'verbose_name_plural': 'notes'},
        ),
        migrations.AlterField(
            model_name='notes',
            name='description',
            field=models.TextField(max_length=1200),
        ),
    ]
